-- Test if pgcrypto accepts $2b$ prefix
-- The hash below is '123456' generated by bcryptjs ($2b$)
-- $2b$10$oFDNNuExZmeZ5Ey6td/LzOm9OYzS4wed.6c5yyjeT0ybLaenIVGsa

SELECT 
  crypt('123456', '$2b$10$oFDNNuExZmeZ5Ey6td/LzOm9OYzS4wed.6c5yyjeT0ybLaenIVGsa') as calculated_hash,
  (crypt('123456', '$2b$10$oFDNNuExZmeZ5Ey6td/LzOm9OYzS4wed.6c5yyjeT0ybLaenIVGsa') = '$2b$10$oFDNNuExZmeZ5Ey6td/LzOm9OYzS4wed.6c5yyjeT0ybLaenIVGsa') as is_match;

-- If is_match is FALSE or calculated_hash is different, then pgcrypto doesn't support $2b$
